[[redirects]]
  from = "/api/v1/Login"
  to = "http://hawas.runasp.net/api/v1/Login"
  status = 200
  force = true

[[redirects]]
  from = "/api/v1/Register"
  to = "http://hawas.runasp.net/api/v1/Register"
  status = 200
  force = true